# Generated by Django 5.2.4 on 2025-08-06 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('personal_trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_gestite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Discipline',
            },
        ),
        migrations.CreateModel(
            name='Corso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('max_partecipanti', models.IntegerField()),
                ('utenti', models.ManyToManyField(blank=True, related_name='corsi_iscritto', to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corsi', to='gestione.disciplina')),
            ],
            options={
                'verbose_name_plural': 'Corsi',
            },
        ),
    ]
