# Generated by Django 5.2.4 on 2025-08-12 14:23

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gestione', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atleti',
            fields=[
            ],
            options={
                'verbose_name': 'Atleta',
                'verbose_name_plural': 'Atleti',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalTrainer',
            fields=[
            ],
            options={
                'verbose_name': 'Personal Trainer',
                'verbose_name_plural': 'Personal Trainers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
