# Generated by Django 5.2.4 on 2025-08-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0002_atleti_personaltrainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='corso',
            name='ora',
            field=models.TimeField(default='12:00'),
            preserve_default=False,
        ),
    ]
