# Generated by Django 5.2.4 on 2025-08-12 20:20

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gestione', '0003_corso_ora'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Atleti',
        ),
        migrations.CreateModel(
            name='Atleta',
            fields=[
            ],
            options={
                'verbose_name': 'Atleta',
                'verbose_name_plural': 'Atleti',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='corso',
            name='data',
            field=models.DateField(),
        ),
    ]
